-- ============================================
-- Sample Documents for Testing RAG
-- ============================================

-- Note: Embeddings will be generated by the backend API
-- These sample documents are inserted without embeddings initially

INSERT INTO documents (
    title,
    content,
    document_type,
    author,
    tags,
    metadata
) VALUES
(
    'Mannlowe Information Services Invoice - DOM-23-24-00088',
    'Invoice Number: DOM-23-24-00088
Date: December 4, 2023
Due Date: December 9, 2023

Vendor: Mannlowe Information Services Private Limited
Address: Chembur, Mumbai, Maharashtra - 400071
Contact: sales@mannlowe.com, +91 96650 18588
GSTIN: 27AAQCM9498N1Z5

Bill To: KSJ Products and Services
Address: Rajasthan

Service Description: ERPNext Implementation - Completion of BBP (Business Blueprint Phase)

Amount Details:
- Base Amount: ₹90,000.00
- IGST (18%): ₹16,200.00
- Total Amount: ₹1,06,200.00

Payment Terms: Net 5 days
Bank Details: HDFC Bank, Account No: 50200012345678',
    'Invoice',
    'System Import',
    ARRAY['invoice', 'finance', 'erp', 'implementation', 'mannlowe'],
    '{"vendor": "Mannlowe Information Services", "invoice_number": "DOM-23-24-00088", "amount": 106200, "currency": "INR", "date": "2023-12-04", "category": "Professional Services", "tax_rate": 0.18}'::jsonb
),
(
    'Freshworks Software License Invoice - FS245576',
    'Invoice Number: FS245576
Date: November 27, 2023
Due Date: December 27, 2023

Vendor: Freshworks Inc.
Address: 2950 S. Delaware Street, Suite 201, San Mateo, CA 94403, USA
Contact: +1 (866) 832 3090
Website: www.freshworks.com

Bill To: Mohammad Haseeb
Company: Petroline Group
Address: United Arab Emirates

Product: Freshservice - Enterprise Annual Plan
Quantity: 2 units
Unit Price: $900.00
Subtotal: $1,800.00
Adjustment: -$150.00
Total Amount: $1,649.99 USD

Subscription Period: November 27, 2023 to November 27, 2024

Features Included:
- Unlimited agents and requesters
- Advanced automation and workflows
- Multi-level approval workflows
- Custom apps and integrations
- 24/7 enterprise support',
    'Invoice',
    'System Import',
    ARRAY['invoice', 'finance', 'software', 'license', 'saas', 'freshworks'],
    '{"vendor": "Freshworks Inc.", "invoice_number": "FS245576", "amount": 1649.99, "currency": "USD", "date": "2023-11-27", "category": "Software License", "subscription_type": "Annual", "product": "Freshservice Enterprise"}'::jsonb
),
(
    'The Decisive Enterprise: Modern Intelligence Stack White Paper',
    'Executive Summary

The Document Problem:
Approximately 80% of enterprise business-critical information is born unstructured - trapped in invoices, contracts, purchase orders, medical reports, and emails. This creates a fundamental conflict where structured business systems (ERPs, CRMs, WMS) are forced to process messy, unstructured data.

The Intelligence Gap:
This represents the chasm between the static logic of old automation and the dynamic reality of business communication. Traditional automation tools expect data in predictable formats, but when document layouts change, templates break, and automation fails.

Core Challenges:
1. Brittle automation systems with high maintenance costs
2. Template-based OCR that breaks with format changes
3. Manual data entry bottlenecks
4. Inability to scale document processing
5. Lack of contextual understanding in automation

The Modern Intelligence Stack:

Layer 1 - Intelligent Document Processing (IDP):
- Advanced computer vision and machine learning models
- Template-free document understanding
- Context-aware field extraction
- Multi-page table processing
- Handwriting recognition
- Accuracy rates up to 99.9%

Layer 2 - Decision Intelligence Engine:
- Business Process Management (BPM) platforms
- Integrated business rules engines
- Automated decision-making workflows
- Human-in-the-loop capabilities
- Straight-through processing for routine cases

Key Technologies:
- DocExtractor: Modern IDP platform for document processing
- Computer Vision: Deep learning models for visual understanding
- Natural Language Processing: Semantic understanding of text
- Business Rules Management: Configurable decision logic
- Workflow Orchestration: End-to-end process automation

Benefits:
- 90% reduction in manual data entry
- 99%+ accuracy in data extraction
- 10x faster document processing
- Seamless handling of format changes
- Scalable automation infrastructure
- Real-time processing capabilities

Implementation Approach:
1. Identify high-volume document workflows
2. Deploy IDP layer for document understanding
3. Configure business rules for decision-making
4. Implement human review for exceptions
5. Monitor and optimize continuously

The future of enterprise automation lies not in rigid templates, but in intelligent systems that understand context, learn from data, and make decisions like humans do.',
    'Research Paper',
    'Enterprise Solutions Team',
    ARRAY['research', 'automation', 'idp', 'ai', 'document-processing', 'enterprise'],
    '{"category": "Technology Research", "year": 2023, "topic": "Document Automation", "technologies": ["IDP", "Computer Vision", "NLP", "BPM"], "industry": "Enterprise Software"}'::jsonb
);

-- ============================================
-- Sample Search History
-- ============================================

INSERT INTO search_history (query, search_type, results_count, user_id) VALUES
('invoice december 2023', 'keyword', 2, 'demo-user'),
('ERP implementation', 'keyword', 1, 'demo-user'),
('software licensing', 'keyword', 1, 'demo-user'),
('document automation', 'keyword', 1, 'demo-user');

-- ============================================
-- Verification
-- ============================================

-- Count documents
SELECT COUNT(*) as total_documents FROM documents;

-- Show document types
SELECT document_type, COUNT(*) as count
FROM documents
GROUP BY document_type;

-- Show all document titles
SELECT id, title, document_type, created_at
FROM documents
ORDER BY created_at DESC;
